### ISSUE TITLE
Little change in Makefiles to allow easy swap to the "WCH-Interrupt-fast" toolchain

### ISSUE THREAD

**Issue by doegox** [hydrausb3/hydrausb3_fw#18]
Hi

If you change in all Makefile as follows
```diff
-BASE_OPTS = -march=rv32imac -mabi=ilp32 -msmall-data-limit=8 $(OPTIM_OPTS) -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections
+RISCV_ARCH ?= rv32imac
+BASE_OPTS = -march=$(RISCV_ARCH) -mabi=ilp32 -msmall-data-limit=8 $(OPTIM_OPTS) -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections
```
then to apply the "WCH-Interrupt-fast" toolchain, one doesn't need to patch the examples as specified in https://github.com/hydrausb3/riscv-none-elf-gcc-xpack/releases/tag/12.2.0-1, but he can just do
```
make COMPILER_PREFIX=riscv-none-elf RISCV_ARCH=rv32imac_zicsr
```

**Comment by bvernoux** [comment]
It is a good idea but such modifications cannot be applied easily today to be compatible with both toolchain especially the MounRiver IDE as it requires some modifications in Eclipse project (which will need to specify COMPILER_PREFIX & RISCV_ARCH)
So to be studied to have something which work easily in both world proprietary toolchain with and without MounRiver IDE and the open source xPack GNU RISC-V Embedded GCC v12.2.0-1 toolchain

**Comment by bvernoux** [comment]
Fixed with commit https://github.com/hydrausb3/hydrausb3_fw/commit/e1707dc9f0c9fe7e609dc8e59b844bff1e47dad4 
Makefile add automatic detection and use of compatible riscv compiler either closed source from MounRiver Studio riscv-none-embed or open source one GCC riscv-none-elf available at https://github.com/hydrausb3/riscv-none-elf-gcc-xpack/releases/
I have tested that Makefile with succes on Windows (MSYS2) and GNU/Linux Ubuntu 20.04 or more
